I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 40, in script
    python:
  File "game/script.rpy", line 41, in <module>
    choices[0] = "Reconsider"
IndexError: list assignment index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 40, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 41, in <module>
    choices[0] = "Reconsider"
  File "renpy/python.py", line 875, in do_mutation
    return method(self, *args, **kwargs)
IndexError: list assignment index out of range

Windows-10-10.0.18362
Ren'Py 7.4.2.1292
Red Scarf 1.0
Wed Feb 10 08:48:49 2021
